###

grpcurl -proto api/protobuf/protofiles/toys/masters.proto -plaintext -d '{"pagination": {"limit": 2,"offset": 3}, "filters": {"search": "test"}}' localhost:8060 masters.MastersService.GetMasters

###

grpcurl -proto api/protobuf/protofiles/toys/toys.proto -plaintext -d '{"pagination": {"limit": 2,"offset": 3}}' localhost:8060 toys.ToysService.GetToys

###

grpcurl -proto api/protobuf/protofiles/toys/toys.proto -plaintext -d '' localhost:8060 toys.ToysService.CountToys


###

grpcurl -proto api/protobuf/protofiles/toys/masters.proto -plaintext -d '{"filters": {"search": "test"}}' localhost:8060 masters.MastersService.CountMasters
