// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/masters_service.go -exclude_interfaces=TagsService,CategoriesService,ToysService,SsoService -package=mockservices
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-toys/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockMastersService is a mock of MastersService interface.
type MockMastersService struct {
	ctrl     *gomock.Controller
	recorder *MockMastersServiceMockRecorder
	isgomock struct{}
}

// MockMastersServiceMockRecorder is the mock recorder for MockMastersService.
type MockMastersServiceMockRecorder struct {
	mock *MockMastersService
}

// NewMockMastersService creates a new mock instance.
func NewMockMastersService(ctrl *gomock.Controller) *MockMastersService {
	mock := &MockMastersService{ctrl: ctrl}
	mock.recorder = &MockMastersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMastersService) EXPECT() *MockMastersServiceMockRecorder {
	return m.recorder
}

// CountMasters mocks base method.
func (m *MockMastersService) CountMasters(ctx context.Context, filters *entities.MastersFilters) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMasters", ctx, filters)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMasters indicates an expected call of CountMasters.
func (mr *MockMastersServiceMockRecorder) CountMasters(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMasters", reflect.TypeOf((*MockMastersService)(nil).CountMasters), ctx, filters)
}

// GetMasterByID mocks base method.
func (m *MockMastersService) GetMasterByID(ctx context.Context, id uint64) (*entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterByID", ctx, id)
	ret0, _ := ret[0].(*entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterByID indicates an expected call of GetMasterByID.
func (mr *MockMastersServiceMockRecorder) GetMasterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterByID", reflect.TypeOf((*MockMastersService)(nil).GetMasterByID), ctx, id)
}

// GetMasterByUserID mocks base method.
func (m *MockMastersService) GetMasterByUserID(ctx context.Context, userID uint64) (*entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterByUserID", ctx, userID)
	ret0, _ := ret[0].(*entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterByUserID indicates an expected call of GetMasterByUserID.
func (mr *MockMastersServiceMockRecorder) GetMasterByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterByUserID", reflect.TypeOf((*MockMastersService)(nil).GetMasterByUserID), ctx, userID)
}

// GetMasters mocks base method.
func (m *MockMastersService) GetMasters(ctx context.Context, pagination *entities.Pagination, filters *entities.MastersFilters) ([]entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasters", ctx, pagination, filters)
	ret0, _ := ret[0].([]entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasters indicates an expected call of GetMasters.
func (mr *MockMastersServiceMockRecorder) GetMasters(ctx, pagination, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasters", reflect.TypeOf((*MockMastersService)(nil).GetMasters), ctx, pagination, filters)
}

// RegisterMaster mocks base method.
func (m *MockMastersService) RegisterMaster(ctx context.Context, masterData entities.RegisterMasterDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterMaster", ctx, masterData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterMaster indicates an expected call of RegisterMaster.
func (mr *MockMastersServiceMockRecorder) RegisterMaster(ctx, masterData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMaster", reflect.TypeOf((*MockMastersService)(nil).RegisterMaster), ctx, masterData)
}

// UpdateMaster mocks base method.
func (m *MockMastersService) UpdateMaster(ctx context.Context, masterData entities.UpdateMasterDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaster", ctx, masterData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaster indicates an expected call of UpdateMaster.
func (mr *MockMastersServiceMockRecorder) UpdateMaster(ctx, masterData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaster", reflect.TypeOf((*MockMastersService)(nil).UpdateMaster), ctx, masterData)
}
