// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/masters_repository.go -exclude_interfaces=TagsRepository,CategoriesRepository,ToysRepository -package=mockrepositories
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-toys/pkg/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockMastersRepository is a mock of MastersRepository interface.
type MockMastersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMastersRepositoryMockRecorder
	isgomock struct{}
}

// MockMastersRepositoryMockRecorder is the mock recorder for MockMastersRepository.
type MockMastersRepositoryMockRecorder struct {
	mock *MockMastersRepository
}

// NewMockMastersRepository creates a new mock instance.
func NewMockMastersRepository(ctrl *gomock.Controller) *MockMastersRepository {
	mock := &MockMastersRepository{ctrl: ctrl}
	mock.recorder = &MockMastersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMastersRepository) EXPECT() *MockMastersRepositoryMockRecorder {
	return m.recorder
}

// GetAllMasters mocks base method.
func (m *MockMastersRepository) GetAllMasters() ([]*entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMasters")
	ret0, _ := ret[0].([]*entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMasters indicates an expected call of GetAllMasters.
func (mr *MockMastersRepositoryMockRecorder) GetAllMasters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMasters", reflect.TypeOf((*MockMastersRepository)(nil).GetAllMasters))
}

// GetMasterByID mocks base method.
func (m *MockMastersRepository) GetMasterByID(id uint64) (*entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterByID", id)
	ret0, _ := ret[0].(*entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterByID indicates an expected call of GetMasterByID.
func (mr *MockMastersRepositoryMockRecorder) GetMasterByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterByID", reflect.TypeOf((*MockMastersRepository)(nil).GetMasterByID), id)
}

// GetMasterByUserID mocks base method.
func (m *MockMastersRepository) GetMasterByUserID(userID uint64) (*entities.Master, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterByUserID", userID)
	ret0, _ := ret[0].(*entities.Master)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterByUserID indicates an expected call of GetMasterByUserID.
func (mr *MockMastersRepositoryMockRecorder) GetMasterByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterByUserID", reflect.TypeOf((*MockMastersRepository)(nil).GetMasterByUserID), userID)
}

// RegisterMaster mocks base method.
func (m *MockMastersRepository) RegisterMaster(masterData entities.RegisterMasterDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterMaster", masterData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterMaster indicates an expected call of RegisterMaster.
func (mr *MockMastersRepositoryMockRecorder) RegisterMaster(masterData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMaster", reflect.TypeOf((*MockMastersRepository)(nil).RegisterMaster), masterData)
}
